version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: eventbrite/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6810
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6810:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog/
      IdentityUrl: http://192.168.0.12:6700
      CallBackUrl: http://localhost:6811
    ports:
      - "6811:80"
    networks:
      - frontend
    depends_on:
      - catalog


  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      MVCClient: http://localhost:6811
    ports:
      - "6700:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartAPI
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      IdentityUrl: http://192.168.0.12:6700
      ConnectionString: basket.data
    ports:
      - "6812:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: eventssqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdata
    ports:
      - "6080:6379"
    networks:
      - backend
